services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  
  UniversityOfCopenhagen\KuPrototype\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  UniversityOfCopenhagen\KuPrototype\EventListener\FileUploadEvent:
    public: true
    tags:
      - name: event.listener
        identifier: 'ku-fileupload-listener'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedEvent
        before: 'redirects'

  UniversityOfCopenhagen\KuPrototype\EventListener\FileReplacedEvent:
    public: true
    tags:
      - name: event.listener
        identifier: 'ku-filereplace-listener'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileReplacedEvent
        before: 'redirects'